server:
  port: 8082
  servlet:
    context-path: /openoa
    
#数据库连接
spring: 
  datasource:
    data-username: root
    password: 
    url: jdbc:mysql://localhost:3306/product?charaterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
